// Regenerates web/src/lib/verify/disposable-domains.generated.ts from the upstream blocklist.
// Run: pnpm --filter web exec tsx scripts/gen-disposable-domains.ts
// Fetches disposable_email_blocklist.conf (one domain per line), lowercases + dedups + sorts, and
// writes the Set module. The committed output is the source of truth at build time; this script is
// dev-only tooling (NOT shipped to the runtime bundle). Refresh on a schedule is Phase 9+.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SOURCE =
  "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf";

const HEADER = `// §5.3 disposable / throwaway email providers. GENERATED — a vendored snapshot of
// github.com/disposable-email-domains (disposable_email_blocklist.conf). This is a LOAD-BEARING
// SECURITY CONTROL, not a perf stub: without the full list, throwaway domains mint a company board +
// badge. Regenerated by scripts/gen-disposable-domains.ts. DO NOT hand-edit.
export const DISPOSABLE_DOMAINS = new Set<string>([`;

async function main() {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`gen-disposable-domains: upstream fetch ${res.status}`);
  const text = await res.text();
  const domains = [
    ...new Set(
      text
        .split("\n")
        .map((l) => l.trim().toLowerCase())
        .filter((l) => /^[a-z0-9.-]+\.[a-z]+$/.test(l)),
    ),
  ].sort();

  const body = domains.map((d) => `  ${JSON.stringify(d)},`).join("\n");
  const out = `${HEADER}\n${body}\n]);\n`;

  const here = dirname(fileURLToPath(import.meta.url));
  const target = join(here, "..", "src", "lib", "verify", "disposable-domains.generated.ts");
  await writeFile(target, out, "utf8");
  console.log(`wrote ${domains.length} disposable domains to ${target}`);
}

void main();
